# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CTD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField()),
                ('pressure', models.FloatField()),
                ('conductivity', models.FloatField(blank=True, null=True)),
                ('datetime', models.DateTimeField()),
                ('measured', models.BooleanField(default=True)),
            ],
        ),
    ]
