# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('icefish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctd',
            name='server_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
