# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icefish', '0002_ctd_server_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='HydrophoneAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wav', models.FilePathField(blank=True, null=True)),
                ('flac', models.FilePathField()),
                ('start_time', models.DateTimeField(db_index=True)),
                ('length', models.PositiveIntegerField()),
                ('spectrograph', models.FilePathField(blank=True, null=True)),
                ('flags', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='ctd',
            name='conductivity',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='ctd',
            name='datetime',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='ctd',
            name='pressure',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='ctd',
            name='temp',
            field=models.FloatField(db_index=True),
        ),
    ]
