# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icefish', '0003_auto_20171030_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctd',
            name='salinity',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
