# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 07:29
# Empty migration generated in order to load default CTD into database

from __future__ import unicode_literals

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('icefish', '0004_ctd_salinity'),
    ]

    operations = [
        #migrations.RunSQL("INSERT INTO ctd ('deployment_start') VALUES ('Reinhardt');")
    ]
