# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 00:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icefish', '0005_auto_20171031_2029'),
        ('icefish', '0007_manual_ctd.py'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTDInstrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployment_start', models.DateTimeField()),
                ('deployment_end', models.DateTimeField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=20, null=True)),
                ('serial', models.CharField(blank=True, max_length=30, null=True)),
                ('depth', models.FloatField(blank=True, null=True)),
                ('coord_x', models.FloatField(blank=True, null=True)),
                ('coord_y', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='hydrophoneaudio',
            old_name='spectrograph',
            new_name='spectrogram',
        ),
        migrations.AddField(
            model_name='ctd',
            name='instrument',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='icefish.CTDInstrument'),
            preserve_default=False,
        ),
    ]
