# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icefish', '0007_manual_ctd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ctd',
            old_name='datetime',
            new_name='dt',
        ),
        migrations.RenameField(
            model_name='ctd',
            old_name='server_datetime',
            new_name='server_dt',
        ),
    ]
