# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icefish', '0008_auto_20171103_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(db_index=True, unique=True)),
                ('wind_speed', models.IntegerField(blank=True, null=True)),
                ('wind_speed_flag', models.IntegerField(blank=True, null=True)),
                ('wind_direction', models.IntegerField(blank=True, null=True)),
                ('air_temp', models.IntegerField(blank=True, null=True)),
                ('air_temp_flag', models.IntegerField(blank=True, null=True)),
                ('sea_level_pressure', models.IntegerField()),
                ('sea_level_pressure_flag', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='hydrophoneaudio',
            name='flac',
            field=models.FilePathField(unique=True),
        ),
        migrations.AlterField(
            model_name='hydrophoneaudio',
            name='wav',
            field=models.FilePathField(blank=True, null=True, unique=True),
        ),
    ]
