# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icefish', '0009_auto_20171107_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='ncdc_id_value',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='wind_direction_flag',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='air_temp_flag',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='sea_level_pressure_flag',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wind_speed_flag',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
