# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icefish', '0011_auto_20171108_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctd',
            name='measured',
        ),
        migrations.AddField(
            model_name='ctd',
            name='flags',
            field=models.TextField(default='M'),
        ),
    ]
