# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icefish', '0013_moovideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='moovideo',
            name='dt',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moovideo',
            name='duration',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moovideo',
            name='height',
            field=models.SmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moovideo',
            name='width',
            field=models.SmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moovideo',
            name='transcoded_path',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
