# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icefish', '0014_auto_20171124_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='moovideo',
            name='bit_rate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
