# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icefish', '0015_moovideo_bit_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='moovideo',
            name='format',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
