# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icefish', '0016_moovideo_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTDFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(max_length=10)),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
                ('ctd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icefish.CTD')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HydrophoneAudioFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(max_length=10)),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
                ('hydrophone_audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icefish.HydrophoneAudio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MOOVideoFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(max_length=10)),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
                ('moo_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icefish.MOOVideo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
