# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icefish', '0017_ctdflag_hydrophoneaudioflag_moovideoflag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctd',
            name='flags',
        ),
        migrations.RemoveField(
            model_name='hydrophoneaudio',
            name='flags',
        ),
        migrations.AlterField(
            model_name='ctdflag',
            name='ctd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='icefish.CTD'),
        ),
        migrations.AlterField(
            model_name='hydrophoneaudioflag',
            name='hydrophone_audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='icefish.HydrophoneAudio'),
        ),
        migrations.AlterField(
            model_name='moovideoflag',
            name='moo_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='icefish.MOOVideo'),
        ),
    ]
