# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icefish', '0018_auto_20171124_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctdflag',
            name='flag',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='hydrophoneaudioflag',
            name='flag',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='moovideoflag',
            name='flag',
            field=models.CharField(max_length=15),
        ),
    ]
