# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icefish', '0019_auto_20171125_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctd',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='icefish.CTDInstrument'),
        ),
        migrations.AlterField(
            model_name='ctd',
            name='weather',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='icefish.Weather'),
        ),
        migrations.AlterField(
            model_name='ctdflag',
            name='ctd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='flags', to='icefish.CTD'),
        ),
        migrations.AlterField(
            model_name='hydrophoneaudioflag',
            name='hydrophone_audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='flags', to='icefish.HydrophoneAudio'),
        ),
        migrations.AlterField(
            model_name='moovideoflag',
            name='moo_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='flags', to='icefish.MOOVideo'),
        ),
    ]
